---  
apiVersion: v1
kind: ServiceAccount
metadata:
  name: spark
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: spark-role
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - '*'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-role
subjects:
- kind: ServiceAccount
  name: spark
  namespace: default

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: thriftserver-cluster
  name: thriftserver-cluster
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thriftserver-cluster
  template:
    metadata:
      labels:
        app: thriftserver-cluster
    spec:
      containers:
      - env:
        - name: SPARK_MODE
          value: thriftserver
        - name: SPARK_MASTER_URL
          value: k8s://https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT)
        - name: SPARK_PUBLIC_DNS
          value: localhost
        - name: SPARK_WEBUI_PORT
          value: "4040"
        - name: SPARK_CORES_MAX
          value: "4"
        - name: SPARK_DRIVER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: dil001/spark:v2.4.4
        readinessProbe:
          httpGet:
            port: 4040
            path: /
          initialDelaySeconds: 5
          periodSeconds: 10        
        livenessProbe:
          httpGet:
            port: 4040
            path: /
          initialDelaySeconds: 15
          timeoutSeconds: 1     
        name: spark-thriftserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4040
          name: http
          protocol: TCP
        - containerPort: 10000
          name: jdbc
          protocol: TCP
      restartPolicy: Always
      serviceAccount: spark

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thriftserver-cluster
  name: thriftserver-cluster
  namespace: default
spec:
  ports:
  - name: web-ui
    port: 4040
    protocol: TCP
    targetPort: http
  - name: jdbc
    port: 10000
    protocol: TCP
    targetPort: jdbc
  selector:
    app: thriftserver-cluster
  type: LoadBalancer