---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: thriftserver-cluster
  name: thriftserver-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thriftserver-cluster
  template:
    metadata:
      labels:
        app: thriftserver-cluster
    spec:
      containers:
      - env:
        - name: SPARK_MODE
          value: thriftserver
        - name: SPARK_MASTER_URL
          value: k8s://https://$(KUBERNETES_SERVICE_HOST):$(KUBERNETES_SERVICE_PORT) 
        - name: SPARK_PUBLIC_DNS
          value: localhost
        - name: SPARK_WEBUI_PORT
          value: "4040"
        - name: SPARK_CORES_MAX
          value: "4"
        - name: SPARK_DRIVER_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        image: dil001/spark:v2.4.4
        name: spark-thriftserver
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 4040
          name: http
          protocol: TCP
        - containerPort: 10000
          name: jdbc
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      serviceAccount: spark

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: thriftserver-cluster
  name: thriftserver-cluster
spec:
  ports:
  - name: web-ui
    port: 4040
    protocol: TCP
    targetPort: http
  - name: jdbc
    port: 10000
    protocol: TCP
    targetPort: jdbc
  selector:
    app: thriftserver-cluster
  type: LoadBalancer
